wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.12.10
    framework: torch
    is_jupyter_run: true
    is_kaggle_kernel: false
    python_version: 3.8.10
    start_time: 1651038492
    t:
      1:
      - 1
      4: 3.8.10
      5: 0.12.10
      8:
      - 1
      - 5
